permalink: /notetree/noteleaf/:title
url: #Your url here
baseurl: /project

# variables
name: NtosKrnl.Win
description: windows kernel,windows driver,windbg,coder
google_verification: null


# File management
include: [".htaccess", "_pages"]
exclude: ["README.md", "LICENSE"]
collections:
  pages:
    output: true
    permalink: /notetree/noteleaf/

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true